name = "anastasia-insurance"
main = "functions/api/recruit.js"
compatibility_date = "2026-04-15"

[env.production]
vars = { }

[[env.production.kv_namespaces]]
binding = "KV"

[build]
command = "echo 'No build step needed'"
